name: kd_fsl105_tfl_squeezenet
data:
    data_path: ./fsl-datasets/
    version: fsl
    sgn: sign
    txt: text
    gls: gloss
    train: fsl.squeezenet.train.gz
    dev: fsl.squeezenet.dev.gz
    test: fsl.squeezenet.test.gz
    feature_size: 1024
    level: word
    txt_lowercase: true
    max_sent_length: 400
    random_train_subset: -1
    random_dev_subset: -1
testing:
    recognition_beam_sizes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    translation_beam_sizes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    translation_beam_alphas:
    - -1
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
training:
    reset_best_ckpt: true
    reset_scheduler: false
    reset_optimizer: false
    random_seed: 42
    model_dir: "./kd_fsl105_squeezenet_model_unf"
    recognition_loss_weight: 0.5        # changed
    translation_loss_weight: 0.5        # changed
    eval_metric: bleu
    optimizer: adam
    learning_rate: 0.001
    batch_size: 32
    num_valid_log: 5
    epochs: 100000      # changed
    early_stopping_metric: eval_metric
    batch_type: sentence
    translation_normalization: batch
    eval_recognition_beam_size: 1
    eval_translation_beam_size: 1
    eval_translation_beam_alpha: -1
    overwrite: true
    shuffle: true
    use_cuda: true
    translation_max_output_length: 30
    keep_last_ckpts: 5
    batch_multiplier: 1
    logging_freq: 100
    validation_freq: 100
    betas:
    - 0.9
    - 0.998
    scheduling: plateau
    learning_rate_min: 1.0e-07
    weight_decay: 0.001
    patience: 8
    decrease_factor: 0.7
    label_smoothing: 0.0
model:
    initializer: xavier
    bias_initializer: zeros
    init_gain: 1.0
    embed_initializer: xavier
    embed_init_gain: 1.0
    tied_softmax: false
    encoder:
        type: transformer
        num_layers: 2       # changed
        num_heads: 8
        embeddings:
            embedding_dim: 256      # changed
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 256    #changed
        ff_size: 1024       # changed
        dropout: 0.1
    decoder:
        type: transformer
        num_layers: 2       # changed
        num_heads: 8
        embeddings:
            embedding_dim: 256      # changed
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 246    # changed
        ff_size: 1024       # changed
        dropout: 0.1